[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
test = 'test'
script = 'script'
optimizer_runs = 1000000
via-ir = true
evm_version = 'shanghai'
gas_reports = ["EscrowSrc", "EscrowDst", "EscrowFactory", "TestEscrowFactory", "Resolver"]

[profile.lite.optimizer_details.yulDetails]
optimizerSteps = ''

[fmt]
line_length = 140
bracket_spacing = true
multiline_func_header = 'params_first'
wrap_comments = true

[fuzz]
runs = 1024

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"
mainnet = "${MAINNET_RPC_URL}"

[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}" }
mainnet = { key = "${ETHERSCAN_API_KEY}" }